#!/bin/bash

sudo apt-get install -y tmate
tmate 

# setup socket and ssh key
sudo socket=$TMATE_TMPDIR/socket
sudo ssh_key=$TMATE_TMPDIR/id_rsa
sudo ssh-keygen -f $ssh_key -t rsa -N ''
# was ensure how to specify key to tmate
eval $(ssh-agent)
sudo ssh-add $ssh_key
# launch detached tmate
sudo tmate -S $socket \
  new-session \
 -d -x 80 -y 25 \
 -s ci-session \
 -n ci-window \
  /bin/bash --login
# wait until it is ready
sudo tmate -S $socket wait tmate-ready
# display the tmate ssh and web connections strings
sudo tmate -S $socket display -p '#{tmate_ssh} # #{tmate_web}'
# Should probably replace this sleep, with a poll mechanism
sleep 9999
